### PR TITLE
Add CI & QA Badges

### PR DESCRIPTION
**Pull request by akabiru**
- [x] Travis CI 
- [ ] Code Climate
- [x] Badge Fury - Gem version badge 
- [x] Code Triage - Open Source Helpers 
- [ ] Inch CI

#30

### CODE REVIEW

**Review by bpleslie — APPROVED** [review]
🎉 Having these badges will be nice!

**Comment by vbrazo** [comment]
@bpleslie we might need some extra help in this repository. There are a few issues regarding the search that are pending. Let us know if you'd be interested in taking a look at them.

**Review by vbrazo — APPROVED** [review]

**Comment by bpleslie** [comment]
@vbrazo definitely! I just forked this repo and am getting things set up locally. I’m planning on looking at the search issue this week :)

**Comment by vbrazo** [comment]
There are a few issues on the faker repository and in this repo as well. @akabiru is the best person to tell you.

**Comment by bpleslie** [comment]
@akabiru let me know of any top priority issues. I'm happy to help!

**Comment by akabiru** [comment]
Cheers guys, great to meet you @bpleslie - migrating some issues now from faker. We could definitely use the help on search! 👍

**Comment by akabiru** [comment]
@bpleslie see #37 #36

**Comment by bpleslie** [comment]
Great to meet you @akabiru! I’ll take a look at those issues and respond with feedback!

**Pull request merged**
