### PR TITLE
Add CodeClimate Configuration

### LINKED ISSUE #30: Migrate FakerBot CI & QA integrations
- [x] Add Travis CI [Build Status](https://travis-ci.com/akabiru/fakerbot) 
- [x] Add Code Climate [Maintainability](https://codeclimate.com/github/faker-ruby/faker-bot/maintainability) [Test Coverage](https://codeclimate.com/github/faker-ruby/faker-bot/test_coverage)
- [x] Add Badge Fury - Gem version badge  [Gem Version](https://badge.fury.io/rb/fakerbot)
- [x] Code Triage - Open Source Helpers  [Open Source Helpers](https://www.codetriage.com/akabiru/fakerbot) 
- [x] Add Badges to ReadMe

### PR DESCRIPTION
**Pull request by akabiru**
Closes #30

### CODE REVIEW

**Comment by akabiru** [comment]
@vbrazo please enable Codeclimate for this Org/repo. https://codeclimate.com/dashboard

**Review by bpleslie — APPROVED** [review]
🎉

**Comment by akabiru** [comment]
> @vbrazo please enable Codeclimate for this Org/repo. https://codeclimate.com/dashboard

@vbrazo any update on this one? 🙂

**Comment by vbrazo** [comment]
Yes, I did. I get this error message when building the repository:

Screen Shot 2019-08-06 at 5 13 40 PM

**Comment by akabiru** [comment]
Oh, thanks! Brakeman is actually rails specific, so we can remove it. https://github.com/presidentbeef/brakeman

**Pull request merged**
